### ISSUE TITLE
Incompatible with python 3

### ISSUE THREAD

**Issue by johncadengo** [alexanderkoumis/opencv-gpu-py#1]
Hi. When I try installing this project, I get an error like this:

```
pip install -e opencv-gpu-py
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "~/opencv-gpu-py/setup.py", line 36, in <module>
        opencv_deps = pkgconfig('opencv')
      File "~/opencv-gpu-py/setup.py", line 18, in pkgconfig
        for key, value in flag_map.iteritems():
    AttributeError: 'dict' object has no attribute 'iteritems'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1
```

Now, when I update the offending lines in `setup.py` to use `.items()` instead of `.iteritems()`, I can get it to be installed, but when I run the test.py, I get an error like this:

```
python test/test.py 
Traceback (most recent call last):
  File "test/test.py", line 5, in <module>
    import cv2gpu
ImportError: ~/opencv-gpu-py/cv2gpu.cpython-35m-x86_64-linux-gnu.so: undefined symbol:
```

Any idea why?

**Comment by HansBouwmeester** [comment]
John, Ran into the same thing. Were you able to solve?

**Comment by angiesasmita** [comment]
@johncadengo @Gra55h0pper 
Hi, I'm facing the same issue. Did you guys manage to solve it? thanks!

**Comment by domninvv** [comment]
Yep, same issue, can't find the way to fix it.

**Comment by TharinduDR** [comment]
Any update with the issue? I am facing the same issue with python 3

**Comment by alviur** [comment]
Same issue here, still not solved

**Comment by alexanderkoumis** [comment]
I hear you guys, I've spent a few hours trying to debug this but wasn't able to get to the bottom of it. I'm fairly busy these days so I likely won't be able to provide a fix soon, if anyone else is familiar with the cpython build process for python3 and would like to take a look I'd greatly appreciate it.
