### ISSUE TITLE
usage in ros : TypeError: argument 1 must be string, not numpy.ndarray

### ISSUE THREAD

**Issue by elpimous** [alexanderkoumis/opencv-gpu-py#4]
Board : Nvidia TX2
Ubuntu 16.04
Ros kinetic

I use your lib as a standard python 2.7 lib, and install like this : 
```
git clone https://github.com/alexanderkoumis/opencv-gpu-py
cd opencv-gpu-py
sudo python setup.py install
```

My progr : 
```
import cv2gpu # for face recognition with cuda cascades
from threading import Thread
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError

cascade_file_gpu = '/home/nvidia/catkin_ws/src/alfred_vision/src/haarcascade_frontalface_default_cuda.xml'
cv2gpu.init_gpu_detector(cascade_file_gpu)

class Image_processing:

	def __init__(self):
		rospy.init_node('generic_Image_processing', anonymous=True)

		self.bridge = CvBridge()
                camera_topic = '/camera/rgb/image_raw'
		self.image_sub = rospy.Subscriber(camera_topic,Image,self.callback)

	def callback(self,data):
	    try:
			self.cv_image = self.bridge.imgmsg_to_cv2(data, "bgr8")
			self.frame = cv2.cvtColor(self.cv_image, cv2.COLOR_BGR2GRAY)
                        self.frame = cv2.resize(self.frame, (0,0), fx=0.5, fy=0.5)
                        cv2.imwrite('color_img.jpg', self.frame)
                        for (x, y, w, h) in cv2gpu.find_faces(self.frame):
                            print(x,y,w,h)
	    except CvBridgeError as e:
			print(e)

def main():
	
  imProcess = Image_processing()
  rospy.spin()

if __name__ == '__main__':
    main()
```

My error : 
```
Error: Problem parsing image path
[ERROR] [1525543228.850955]: bad callback: <bound method Image_processing.callback of <__main__.Image_processing instance at 0x7f8eeae4d0>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/nvidia/catkin_ws/src/alfred_vision/src/face_tracking_cuda.py", line 44, in callback
    for (x, y, w, h) in cv2gpu.find_faces(self.frame):
TypeError: argument 1 must be string, not numpy.ndarray
Error: Problem parsing image path
[ERROR] [1525543228.850955]: bad callback: <bound method Image_processing.callback of <__main__.Image_processing instance at 0x7f8eeae4d0>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/nvidia/catkin_ws/src/alfred_vision/src/face_tracking_cuda.py", line 44, in callback
    for (x, y, w, h) in cv2gpu.find_faces(self.frame):
TypeError: argument 1 must be string, not numpy.ndarray
```

This your last version install !
Perhaps I missed anything ?

Thanks a lot, Alexander
Vincent

**Comment by elpimous** [comment]
Alexander, solved with your link !  Could you delete issue ? 
Thanks a lot for your help
